print("Que la chupe Ebner pinche pendejo puto")
print("Que la chupe Ebner pinche pendejo puto")
print("Que la chupe Ebner pinche pendejo puto")
print("Que la chupe Ebner pinche pendejo puto")
print("Que la chupe Ebner pinche pendejo puto")
print("Que la chupe Ebner pinche pendejo puto")