import tkinter as tk
from tkinter import messagebox
def calcular():
    try:
        nombre = txtEmpleado.get()
        horas = float(txtHoras.get())
        costo = float(txtCosto.get())
        sueldo_basico = horas * costo
        sueldo_bruto = sueldo_basico * 1.20
        descuento = sueldo_bruto * 0.12
        sueldo_neto = sueldo_bruto - descuento
        lblBasico.config(text=f"${sueldo_basico:.2f}")
        lblBruto.config(text=f"${sueldo_bruto:.2f}")
        lblDescuento.config(text=f"${descuento:.2f}")
        lblNeto.config(text=f"${sueldo_neto:.2f}")
    except:
        messagebox.showerror("Error", "Ingresa valores válidos")
def limpiar():
    txtEmpleado.delete(0, tk.END)
    txtHoras.delete(0, tk.END)
    txtCosto.delete(0, tk.END)
    lblBasico.config(text="$0.00")
    lblBruto.config(text="$0.00")
    lblDescuento.config(text="$0.00")
    lblNeto.config(text="$0.00")
ventana = tk.Tk()
ventana.title("Control de Pago de Empleados")
ventana.geometry("450x450")
ventana.configure(padx=20, pady=20)
frame_entradas = tk.LabelFrame(ventana, text=" Datos del Empleado ", padx=10, pady=10)
frame_entradas.pack(fill="x", pady=5)
tk.Label(frame_entradas, text="Empleado:").grid(row=0, column=0, sticky="w", pady=2)
txtEmpleado = tk.Entry(frame_entradas, width=30)
txtEmpleado.grid(row=0, column=1, padx=5, pady=2)
tk.Label(frame_entradas, text="Horas trabajadas:").grid(row=1, column=0, sticky="w", pady=2)
txtHoras = tk.Entry(frame_entradas, width=15)
txtHoras.grid(row=1, column=1, sticky="w", padx=5, pady=2)
tk.Label(frame_entradas, text="Costo por hora:").grid(row=2, column=0, sticky="w", pady=2)
txtCosto = tk.Entry(frame_entradas, width=15)
txtCosto.grid(row=2, column=1, sticky="w", padx=5, pady=2)
frame_botones = tk.Frame(ventana, pady=10)
frame_botones.pack(fill="x")
tk.Button(frame_botones, text="Procesar", command=calcular, width=10, bg="#e1f5fe").pack(side="left", padx=5)
tk.Button(frame_botones, text="Limpiar", command=limpiar, width=10).pack(side="left", padx=5)
tk.Button(frame_botones, text="Salir", command=ventana.quit, width=10, bg="#ffebee").pack(side="right", padx=5)
frame_resultados = tk.LabelFrame(ventana, text=" Resumen de Pago ", padx=10, pady=10)
frame_resultados.pack(fill="x", pady=5)
tk.Label(frame_resultados, text="Sueldo Básico:").grid(row=0, column=0, sticky="w")
lblBasico = tk.Label(frame_resultados, text="$0.00", font=("Arial", 10, "bold"))
lblBasico.grid(row=0, column=1, sticky="w", padx=10)
tk.Label(frame_resultados, text="Sueldo Bruto (Basico + 20%):").grid(row=1, column=0, sticky="w")
lblBruto = tk.Label(frame_resultados, text="$0.00", font=("Arial", 10, "bold"), fg="green")
lblBruto.grid(row=1, column=1, sticky="w", padx=10)
tk.Label(frame_resultados, text="Descuento (12%):").grid(row=2, column=0, sticky="w")
lblDescuento = tk.Label(frame_resultados, text="$0.00", font=("Arial", 10, "bold"), fg="red")
lblDescuento.grid(row=2, column=1, sticky="w", padx=10)
tk.Label(frame_resultados, text="Sueldo Neto:", font=("Arial", 11, "bold")).grid(row=3, column=0, sticky="w", pady=(10,0))
lblNeto = tk.Label(frame_resultados, text="$0.00", font=("Arial", 12, "bold"), fg="blue")
lblNeto.grid(row=3, column=1, sticky="w", padx=10, pady=(10,0))
ventana.mainloop()