import oracledb
from .base import Database

class OracleDatabase(Database):
    def __init__(self, user="appuser", password="apppassword", dsn="localhost:1521/XEPDB1"):
        self.user = user
        self.password = password
        self.dsn = dsn
        self.conexion = None

    def conectar(self):
        try:
            self.conexion = oracledb.connect(
                user=self.user,
                password=self.password,
                dsn=self.dsn
            )
            cursor = self.conexion.cursor()
            try:
                cursor.execute("""
                CREATE TABLE usuarios (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre VARCHAR2(255) NOT NULL,
                    correo VARCHAR2(255) UNIQUE NOT NULL,
                    password VARCHAR2(255) NOT NULL
                )
                """)
                self.conexion.commit()
            except oracledb.DatabaseError as e:
                error, = e.args
                if error.code == 955: 
                    pass
                else:
                    raise
            print("✅ Conexión a Oracle (Docker) establecida.")
        except Exception as e:
            print(f"❌ Error conectando a Oracle: {e}")

    def guardar_usuario(self, nombre, correo, password):
        if not self.conexion:
            self.conectar()
        try:
            cursor = self.conexion.cursor()
            cursor.execute(
                "INSERT INTO usuarios(nombre, correo, password) VALUES(:1, :2, :3)",
                (nombre, correo, password)
            )
            self.conexion.commit()
            print(f"✅ Usuario {nombre} guardado en Oracle.")
        except Exception as e:
            print(f"❌ Error guardando en Oracle: {e}")

    def buscar_usuario(self, correo, password):
        if not self.conexion:
            self.conectar()
        try:
            cursor = self.conexion.cursor()
            cursor.execute(
                "SELECT * FROM usuarios WHERE correo = :1 AND password = :2",
                (correo, password)
            )
            return cursor.fetchone()
        except Exception as e:
            print(f"❌ Error buscando en Oracle: {e}")
            return None

    def cerrar(self):
        if self.conexion:
            self.conexion.close()
            print("Conexión Oracle cerrada.")
